[package]
name = "async-util"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.9.0", features = ["unstable"] }
futures = "0.3.12"
pin-project = "1.0.4"
event-listener = "2.5.1"
async-channel = "1.5.1"
ondrop = "0.1.0"
ctrlc = "3.1.7"
async-weighted-semaphore = "0.1.0"
util = { path = "../util" }



