[package]
name = "async-condvar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"

[dev-dependencies]
tokio = { version = "1.10.0", features = ["rt", "macros"] }