[package]
name = "termio"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
byteorder = "1.3.4"
util = {path = "../util"}
unicode-segmentation = "1.6.0"
serde_derive = "1.0"
serde = "1.0"
rand = "0.7.3"
lazy_static = "1.4.0"
strum = "0.18.0"
strum_macros = "0.18.0"
backtrace = "0.3"