[package]
name = "termio"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#getopts = "0.2.21"
#libc = "0.2.68"
itertools = "0.9.0"
#strum = "0.18.0"
#strum_macros = "0.18.0"
#lazy_static = "1.4.0"
#arrayvec = "0.5.1"
#paste = "0.1"
byteorder = "1.3.4"
#rand = "0.7.3"
util = {path = "../util"}