[package]
name = "serde-any"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.127"
bincode = "1.3.3"
serde_json = "1.0.66"