[package]
name = "async-semaphore"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

[dependencies]
atomic = "0.5.0"

[dev-dependencies]
rand = "0.7.3"
async-std = "1.6.3"

[dev-dependencies.futures]
version = "0.3.5"
features = ["thread-pool"]

